// <auto-generated />
namespace Datacle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fixup7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixup7));
        
        string IMigrationMetadata.Id
        {
            get { return "201406220531470_fixup7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
